/**
 * storageTopoService.js
 * Topologie de stockage — baies SAN/NAS, volumes, associations hôtes.
 * Données de simulation représentant l'infrastructure SBEE.
 */

const STORAGE_CONTROLLERS = [
  {
    id: 'san-hpe-msa',
    name: 'HPE MSA 2060 SAN',
    type: 'SAN',
    vendor: 'HPE',
    model: 'MSA 2060 Gen2',
    ip: '192.168.100.10',
    protocol: 'Fibre Channel',
    status: 'online',
    totalCapacityGB: 24576,
    usedCapacityGB: 16800,
    iopsTotal: 85000,
    throughputMBs: 4200,
    raidType: 'RAID-6',
    diskCount: 24,
    diskType: 'SSD+SAS',
    firmware: '2.4.12',
    location: 'Rack-A1 — U18',
  },
  {
    id: 'nas-synology',
    name: 'Synology RS3621xs+',
    type: 'NAS',
    vendor: 'Synology',
    model: 'RS3621xs+',
    ip: '192.168.100.20',
    protocol: 'NFS / SMB',
    status: 'online',
    totalCapacityGB: 36864,
    usedCapacityGB: 22300,
    iopsTotal: 22000,
    throughputMBs: 1800,
    raidType: 'SHR-2',
    diskCount: 16,
    diskType: 'HDD NAS',
    firmware: 'DSM 7.2',
    location: 'Rack-A2 — U12',
  },
  {
    id: 'local-esxi01',
    name: 'Stockage Local ESXi-01',
    type: 'Local',
    vendor: 'HPE',
    model: 'Smart Array P408i-a',
    ip: '192.168.10.11',
    protocol: 'SATA/SAS Local',
    status: 'online',
    totalCapacityGB: 1800,
    usedCapacityGB: 450,
    iopsTotal: 15000,
    throughputMBs: 600,
    raidType: 'RAID-1',
    diskCount: 2,
    diskType: 'SSD',
    firmware: '-',
    location: 'Rack-A1 — U6',
  },
  {
    id: 'local-esxi02',
    name: 'Stockage Local ESXi-02',
    type: 'Local',
    vendor: 'HPE',
    model: 'Smart Array P408i-a',
    ip: '192.168.10.12',
    protocol: 'SATA/SAS Local',
    status: 'online',
    totalCapacityGB: 1800,
    usedCapacityGB: 380,
    iopsTotal: 15000,
    throughputMBs: 600,
    raidType: 'RAID-1',
    diskCount: 2,
    diskType: 'SSD',
    firmware: '-',
    location: 'Rack-A1 — U8',
  },
  {
    id: 'local-esxi03',
    name: 'Stockage Local ESXi-03',
    type: 'Local',
    vendor: 'HPE',
    model: 'Smart Array E208i-a',
    ip: '192.168.10.13',
    protocol: 'SATA/SAS Local',
    status: 'online',
    totalCapacityGB: 1200,
    usedCapacityGB: 290,
    iopsTotal: 12000,
    throughputMBs: 400,
    raidType: 'RAID-1',
    diskCount: 2,
    diskType: 'SSD',
    firmware: '-',
    location: 'Rack-B1 — U4',
  },
];

const VOLUMES = [
  // SAN HPE MSA
  {
    id: 'vol-san-prod-lun01',
    name: 'SAN-PROD-LUN01',
    controllerId: 'san-hpe-msa',
    type: 'VMFS',
    protocol: 'FC',
    capacityGB: 4096,
    usedGB: 2800,
    iops: 12000,
    latencyMs: 1.2,
    mountedOn: ['esxi-01', 'esxi-02'],
    vms: ['SICA-APP-01', 'SICA-DB-01', 'EXCHANGE-01', 'PASSERELLE-PAY-01', 'SICA-APP-02', 'SICA-DB-02', 'ERP-FINANCE-01'],
  },
  {
    id: 'vol-san-prod-lun02',
    name: 'SAN-PROD-LUN02',
    controllerId: 'san-hpe-msa',
    type: 'VMFS',
    protocol: 'FC',
    capacityGB: 2048,
    usedGB: 980,
    iops: 6000,
    latencyMs: 1.4,
    mountedOn: ['esxi-01'],
    vms: ['SICA-DB-01'],
  },
  {
    id: 'vol-san-arch',
    name: 'SAN-ARCHIVE-LUN01',
    controllerId: 'san-hpe-msa',
    type: 'VMFS',
    protocol: 'FC',
    capacityGB: 8192,
    usedGB: 4200,
    iops: 2500,
    latencyMs: 2.8,
    mountedOn: ['esxi-02'],
    vms: ['ERP-FINANCE-01', 'SBEE-MONITOR'],
  },
  // NAS Synology
  {
    id: 'vol-nas-shared',
    name: 'NAS-SHARED-NFS01',
    controllerId: 'nas-synology',
    type: 'NFS',
    protocol: 'NFS v4.1',
    capacityGB: 8192,
    usedGB: 3500,
    iops: 4000,
    latencyMs: 3.5,
    mountedOn: ['esxi-01', 'esxi-02'],
    vms: ['AD-DC-01', 'DNS-DHCP-01', 'AD-DC-02', 'SBEE-MONITOR', 'PROXY-WEB'],
  },
  {
    id: 'vol-nas-backup',
    name: 'NAS-BACKUP-NFS01',
    controllerId: 'nas-synology',
    type: 'NFS',
    protocol: 'NFS v4.1',
    capacityGB: 16384,
    usedGB: 9800,
    iops: 2000,
    latencyMs: 4.2,
    mountedOn: ['esxi-03'],
    vms: ['VEEAM-BR-01', 'BACKUP-REPO-01'],
  },
  {
    id: 'vol-nas-iso',
    name: 'NAS-ISO-STORE',
    controllerId: 'nas-synology',
    type: 'NFS',
    protocol: 'NFS v4.1',
    capacityGB: 2048,
    usedGB: 800,
    iops: 500,
    latencyMs: 5.0,
    mountedOn: ['esxi-01', 'esxi-02', 'esxi-03'],
    vms: [],
  },
  // Local
  {
    id: 'vol-local-01',
    name: 'Datastore-Local-01',
    controllerId: 'local-esxi01',
    type: 'VMFS',
    protocol: 'Local SATA',
    capacityGB: 1800,
    usedGB: 450,
    iops: 3000,
    latencyMs: 0.8,
    mountedOn: ['esxi-01'],
    vms: [],
  },
  {
    id: 'vol-local-02',
    name: 'Datastore-Local-02',
    controllerId: 'local-esxi02',
    type: 'VMFS',
    protocol: 'Local SATA',
    capacityGB: 1800,
    usedGB: 380,
    iops: 3000,
    latencyMs: 0.8,
    mountedOn: ['esxi-02'],
    vms: [],
  },
  {
    id: 'vol-local-03',
    name: 'Datastore-Local-03',
    controllerId: 'local-esxi03',
    type: 'VMFS',
    protocol: 'Local SATA',
    capacityGB: 1200,
    usedGB: 290,
    iops: 2500,
    latencyMs: 0.9,
    mountedOn: ['esxi-03'],
    vms: ['DMZ-WEB-01', 'DMZ-WEB-02', 'VPN-GATEWAY'],
  },
];

function getStorageTopology() {
  const totalGB = STORAGE_CONTROLLERS.reduce((s, c) => s + c.totalCapacityGB, 0);
  const usedGB  = STORAGE_CONTROLLERS.reduce((s, c) => s + c.usedCapacityGB, 0);
  return {
    summary: {
      totalCapacityGB: totalGB,
      usedCapacityGB: usedGB,
      freeCapacityGB: totalGB - usedGB,
      usedPercent: parseFloat(((usedGB / totalGB) * 100).toFixed(1)),
      controllerCount: STORAGE_CONTROLLERS.length,
      volumeCount: VOLUMES.length,
    },
    controllers: STORAGE_CONTROLLERS,
    volumes: VOLUMES,
  };
}

function getStorageStats() {
  return {
    totalIops: STORAGE_CONTROLLERS.reduce((s, c) => s + c.iopsTotal, 0),
    totalThroughputMBs: STORAGE_CONTROLLERS.reduce((s, c) => s + c.throughputMBs, 0),
    volumesByType: VOLUMES.reduce((acc, v) => {
      acc[v.type] = (acc[v.type] || 0) + 1;
      return acc;
    }, {}),
  };
}

module.exports = { getStorageTopology, getStorageStats };
