import asyncio
import json
import logging
from celery import shared_task
from sqlalchemy.ext.asyncio import AsyncSession
from packages.db.engine import DatabaseManager
from packages.db.models.metric import MetricPoint, MetricSeries
from packages.db.models.asset import Asset
from sqlalchemy.future import select

logger = logging.getLogger(__name__)

# Single DB Manager for celery worker threads
db = DatabaseManager()

@shared_task(name="metrics.process_batch")
def process_metric_batch(batch_json_string: str):
    """
    Consumes a batch of points generated by the Kafka consumer or directly queued.
    Resolves Asset UUIDs against labels, creates MetricSeries if missing,
    then uses fast bulk insert (COPY protocol representation) for TimescaleDB.
    """
    asyncio.run(_async_process_batch(json.loads(batch_json_string)))

async def _async_process_batch(points: list[dict]):
    async with db.get_session() as session:
        # Resolve series IDs
        # To avoid lookup on every point, we'd use a Redis Cache or local LRU.
        # This implementation does a simple DB query per unique asset/metric tuple for correctness.
        seen_series = {}
        
        for p in points:
            asset_ref = p.get('asset_id')
            metric_name = p.get('metric_name')
            
            cache_key = f"{asset_ref}_{metric_name}"
            
            if cache_key not in seen_series:
                # Resolve Asset -> Series
                stmt = select(MetricSeries).join(Asset).where(
                    Asset.id == asset_ref,
                    MetricSeries.name == metric_name
                ) # Note: real prod would use a materialized view or redis cache of (name, asset.id)->series.id
                series = (await session.execute(stmt)).scalars().first()
                if series:
                    seen_series[cache_key] = series.id
                else:
                    # Auto-create if not exists
                    try:
                        new_s = MetricSeries(
                            name=metric_name, 
                            asset_id=asset_ref,
                            unit="unknown"
                        )
                        session.add(new_s)
                        await session.flush()
                        seen_series[cache_key] = new_s.id
                    except Exception as e:
                        logger.warning(f"Failed resolving series for {cache_key}: {e}")
                        continue
            
            # Map the point
            if cache_key in seen_series:
                from datetime import datetime
                # Handle ts correctly regardless of string or int format
                ts = datetime.fromtimestamp(p['timestamp'])
                
                mp = MetricPoint(
                    series_id=seen_series[cache_key],
                    value=p['value'],
                    ts=ts,
                    labels=p.get('labels')
                )
                session.add(mp)
        
        # Commit all point inserts
        # Asyncpg optimizations using execute_many are triggered by alchemy behind the scenes for batched adds.
        await session.commit()
